name: Test environment deployment

on:
    # push:
    #     branches: ["test"]
    #     paths:
    #         - "src/**"
    #         - "**/*.js"
    #         - "Dockerfile"
    workflow_dispatch:

jobs:
    Build-image:
        permissions:
            contents: read 
            security-events: write
        name: Build and scan image
        runs-on: ubuntu-latest
        steps:
            # -
            #     name: Set up Docker Buildx
            #     uses: docker/setup-buildx-action@v3
            # -
            #     name: Login to Docker Hub
            #     uses: docker/login-action@v3
            #     with:
            #         username: ${{ secrets.DOCKERHUB_USERNAME }}
            #         password: ${{ secrets.DOCKERHUB_TOKEN }}
            # -
            #     name: Build and push
            #     uses: docker/build-push-action@v5
            #     with:
            #         push: true
            #         tags: tonyq2k3/auth-microservice:test-${{ github.sha }}
            - 
                name: Checkout code
                uses: actions/checkout@v4

            - 
                name: Build an image from Dockerfile
                run: |
                    docker build -t tonyq2k3/auth-microservice:test .

            - 
                name: Run Trivy vulnerability scanner
                uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
                with:
                    image-ref: 'tonyq2k3/auth-microservice:test'
                    format: 'template'
                    template: '@/contrib/sarif.tpl'
                    output: 'trivy-results.sarif'
                    severity: 'CRITICAL,HIGH'
    
            - 
                name: Upload Trivy scan results to GitHub Security tab
                uses: github/codeql-action/upload-sarif@v3
                with:
                    sarif_file: 'trivy-results.sarif'
        
    # Update-manifest:
    #     runs-on: ubuntu-latest
    #     needs: Build-image
    #     if: ${{ success() }}
    #     steps:
    #         -
    #             name: Checkout infrastructure repo
    #             uses: actions/checkout@v3
    #             with:
    #                 repository: NT548-DevOps-Group2/infrastructures
    #                 ref: 'main'
    #                 token: ${{ secrets.GIT_TOKEN }}

    #         -   
    #             name: Setup image tag
    #             run: echo "SHORT_SHA=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_ENV
    #         -
    #             name: Update frontend manifest
    #             run: |
    #                 git config --global user.email "ntbquoc2015@gmail.com"
    #                 git config --global user.name "TonyQ2k3"
    #                 sed -i 's#tonyq2k3/auth-microservice:[^[:space:]]*$#tonyq2k3/auth-microservice:test-${{ github.sha }}#g' ./test/microservices/auth-service-deploy.yaml
    #                 git add ./test/microservices/auth-service-deploy.yaml
    #                 git commit -m "Update auth service version to test-${{ github.sha }} in test environment"
    #                 git push origin main